name: Modul 1 - CI Pipeline Pertama

# Pipeline ini berjalan otomatis setiap ada push ke branch main
on:
  push:
    branches: [ "main" ]

jobs:
  test-app:
    runs-on: ubuntu-latest

    steps:
      # 1. Gunakan v5 untuk mendukung runtime Actions terbaru
      - name: Checkout Repository
        uses: actions/checkout@v5

      # 2. Gunakan v5 untuk setup Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # 3. Jalankan pengujian kode otomatis
      - name: Run Application Check
        run: |
          python app.py
