name: Modul 1 - CI Pipeline Pertama

# Pipeline ini berjalan otomatis setiap ada push ke branch main
on:
  push:
    branches: [ "main" ]

jobs:
  test-app:
    runs-on: ubuntu-latest

    steps:
      # 1. Ambil kode dari repository
      - name: Checkout Repository
        uses: actions/checkout@v5

      # 2. Jalankan pengujian kode menggunakan Python bawaan runner
      - name: Run Application Check
        run: |
          python3 app.py
