name: Modul 1 - CI Pipeline Pertama

# Pipeline ini berjalan otomatis setiap ada push ke branch main
on:
  push:
    branches: [ "main" ]

jobs:
  test-app:
    runs-on: ubuntu-latest

    steps:
      # 1. Ambil kode dari repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. Setup environment Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 3. Jalankan pengujian kode otomatis
      - name: Run Application Check
        run: |
          python app.py
